name: Dismiss Stale PR Approvals

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  actions: read
  pull-requests: write

jobs:
  dismiss_approvals:
    runs-on: ubuntu-latest
    steps:
      - uses: bazelbuild/continuous-integration/actions/bcr-pr-reviewer@bd6a90eceb738c010fd1a9b472e8b6c894e6ea4e
        with:
          token: ${{ github.token }}
          action-type: dismiss_approvals
